"""Render quotes.jsonl as CATALOG.md, grouped by primary label."""
import json
import re
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
QUOTES = HERE / 'quotes' / 'quotes.jsonl'
SOURCES = HERE / 'quotes' / 'sources.json'
TAXONOMY = HERE / 'TAXONOMY.md'
OUT = HERE / 'CATALOG.md'


def labels_in_order():
    return re.findall(r'^\| `([ABC]\d_[a-z_]+)` \|', TAXONOMY.read_text(encoding='utf-8'), re.M)


def md(s):
    return s.replace('|', '\\|').replace('\n', ' ')


def main():
    rows = [json.loads(l) for l in QUOTES.read_text(encoding='utf-8').splitlines() if l.strip()]
    sources = json.load(open(SOURCES, encoding='utf-8'))
    by_primary = defaultdict(list)
    any_label = Counter()
    for r in rows:
        by_primary[r['primary_label']].append(r)
        for l in r['labels']:
            any_label[l] += 1
    order = labels_in_order()
    lines = ['# Catalog of help-line moments', '',
             'Generated by `scripts/render_catalog.py` from `quotes/quotes.jsonl`. Do not edit by hand.',
             '', f'{len(rows)} quotes from {len({r["source_id"] for r in rows})} sources. '
             'Every quote is verbatim and verified against a cached copy of its source by '
             '`scripts/verify_quotes.py`. Labels are retrospective and speculative; see `TAXONOMY.md`.',
             '', '## Coverage', '', '| Label | Primary | Any |', '|---|---|---|']
    for l in order:
        lines.append(f'| `{l}` | {len(by_primary.get(l, []))} | {any_label.get(l, 0)} |')
    missing = [l for l in order if any_label.get(l, 0) == 0]
    if missing:
        lines += ['', 'Not found in the sources reviewed: ' + ', '.join(f'`{l}`' for l in missing) + '.']
    lines += ['', '## By source', '', '| source_id | Title | Rows |', '|---|---|---|']
    per_source = Counter(r['source_id'] for r in rows)
    for sid, n in per_source.most_common():
        title = sources.get(sid, {}).get('title', sid)
        url = sources.get(sid, {}).get('url', '')
        lines.append(f'| `{sid}` | [{md(title)}]({url}) | {n} |' if url else f'| `{sid}` | {md(title)} | {n} |')
    for l in order:
        group = by_primary.get(l)
        if not group:
            continue
        lines += ['', f'## {l}', '',
                  '| id | Actor | Quote | Kind | Counterfactual | Timing | Conf. | Locator |',
                  '|---|---|---|---|---|---|---|---|']
        for r in sorted(group, key=lambda x: x['id']):
            extra = ', '.join(x for x in r['labels'] if x != l)
            lines.append('| `{id}` | {actor} | "{quote}"{extra} | {kind} | {cf} | {t} | {c} | {loc} |'.format(
                id=r['id'], actor=md(r['actor']), quote=md(r['quote']),
                extra=f' (also {extra})' if extra else '', kind=r['quote_kind'],
                cf=r['counterfactual'], t=r['timing'], c=r['speculation_confidence'],
                loc=md(f"{r['source_id']} · {r['locator']}")))
    lines += ['', '## Reading the table', '',
              '- *Kind*: `published_cot` is the agent\'s own reasoning as reproduced by a source; '
              '`investigator_paraphrase` is a paraphrase the source marks as such; `posted_message` is text '
              'the agent wrote to a public surface; `system_card` and `paper_transcript` are excerpts from '
              'those documents; `author_narrative` is the source\'s description when no agent text exists.',
              '- *Counterfactual*: what a help line could have offered at that moment.',
              '- *Conf.*: how plausible it is that the agent would have called; `low` means a reader can '
              'imagine the call but the agent shows no sign of wanting one.',
              '- Every row has a `not_established` field in the JSONL that names what the quote does not prove.']
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'{len(rows)} rows -> {OUT}')


if __name__ == '__main__':
    main()
